<a href="https://colab.research.google.com/github/Shrutigupta102005/machine_learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
# numpy
#Performance measurement
#%timeit is an python function, which can be used to check the time taken by a particular piece of code (A single execution statement, or a single method)

In [47]:
list = [1,2,3,4,5,6,7]
print(list)
print(list[3])
#list is slow ,expensive in terms of memory --- therefore we use numpy

[1, 2, 3, 4, 5, 6, 7]
4


In [48]:
import numpy as np
# to install numpy -- pip install np
# data type of numpy array is ndarray(n-dimensional array)
list2 = np.array([1,2,3,4,5,6,7]) # have dtype inside
print(list2)
print(list2[3])
#shape -- number of element
list2.shape

[1 2 3 4 5 6 7]
4


(7,)

In [49]:
#range
a=np.arange(5,12,2)
print(a)
#Zeroes
b=np.zeros(3)
print(b)
# Multi dimensionl Zeroes
b=np.zeros((2,2))
print(b)
#ones
c=np.ones(5)
print(c)
#full
d=np.full(2,5)
print(d)


[ 5  7  9 11]
[0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1.]
[5 5]


In [50]:
# convert python list to numpy
sh = [2,3,4,5,6]
shruti = np.array(sh)
print(shruti)
#type
print(type(shruti))

[2 3 4 5 6]
<class 'numpy.ndarray'>


In [51]:
# slicing numpy
print(shruti[1:4])
md = [ [1,2,3],[4,5,6]]
#multidimensional array
var =md[0:2][0:2]
print(var)

[3 4 5]
[[1, 2, 3], [4, 5, 6]]


In [52]:


print(np.sqrt( shruti))
print(np.absolute(shruti))
print(np.exp(shruti))
print(np.max(shruti))
print(np.min(shruti))
print(np.sort(shruti))
print(np.sign(shruti))
# refer to numpy docs universal function

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[2 3 4 5 6]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
6
2
[2 3 4 5 6]
[1 1 1 1 1]


In [54]:
# copy vs view
shubh =np.copy(shruti)
dhruv = shruti.view() # changes to orignal will be seen in copy
print(shubh)
print(dhruv)
shruti[0] = 12
shubh[0]=99
print(shubh)
print(dhruv)
print(shruti)

[2 3 4 5 6]
[2 3 4 5 6]
[99  3  4  5  6]
[12  3  4  5  6]
[12  3  4  5  6]


In [59]:
 #shape and reshape array
 #creating a 1d array
 ajay = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
 print(ajay)
 print(ajay.shape)
 #creating a 2d array
 ruby = np.array([[1,2,3,4],[5,6,7,8]])
 print(ruby)
 print(ruby.shape)
 """ to iterate over a array you can use multiple loop
 or simply you can use nditer method  """
 for x in np.nditer(ruby):
  print(x)
 # reshape
 om = ajay.reshape(4,3)
 print(om)
 print(om.shape)
 #flatten array to 1d
 babu = om.reshape(-1)
 print(babu)
 print(babu.shape)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
1
2
3
4
5
6
7
8
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [61]:
# searching in arrays
ajay = np.array([1,2,3,4,5,4,4])
x = np.where(ajay == 4)   # return  tuple of index
print(x)


(array([3, 5, 6]),)
